### PR TITLE
Correct route problem in OpenShift template

### LINKED ISSUE #468: incorrect route created in OCP v4
When deploying to openshift - the template provides an unqualifed hostname matching the service name. This is an error and results in creating an application route that is simply:

```
http://nlu-code-pattern
```

### PR DESCRIPTION
**Pull request by timroster**
comments out the `value` for `APPLICATION_DOMAIN` allowing OpenShift to automatically assign a working hostname for the route.

Fixes #468 

Signed-off-by: Tim Robinson <timroster@gmail.com>

### CODE REVIEW

**Comment by timroster** [comment]
@markstur can you review and merge if ok?

**Review by markstur — APPROVED** [review]
Thanks, Tim!

**Review by markstur — APPROVED** [review]

**Review by markstur — APPROVED** [review]
lgtm

**Comment by markstur** [comment]
@timroster Apparently I'm not authorized to merge to this repo.

**Comment by timroster** [comment]
@markstur oops! thanks for reviewing. @jmeis ?

**Comment by timroster** [comment]
@jmeis - I found other problems in the openshift template file (source strategy using an image from `docker.io`) and also missing an example for setting `NATURAL_LANGUAGE_UNDERSTANDING_AUTH_TYPE` in the `.env.example` for the IBM Cloud PaaS service. I have fixes for these and the pattern is working on OCP v4

Ok to push these to the same branch to get them all merged, or do you prefer a new issue and PR?

**Comment by jmeis** [comment]
@timroster you can use the same branch. However, we are going to deprecate and archive this starter kit on February 18 FYI.

**Comment by timroster** [comment]
@jmeis thanks and noted. Pushed additional fixes on this branch. Ready for review and merge if ok.

**Pull request merged**
